import { PageHero } from '../components/common/PageHero'
import { TeacherCard } from '../components/cards/TeacherCard'
import { teachers } from '../data/teachers'
import { useSeo } from '../hooks/useSeo'

const milestones=[['2017','Một phòng piano, hai giáo viên và niềm tin rằng ai cũng có thể học nhạc.'],['2020','Ra mắt chương trình lộ trình cá nhân hóa và báo cáo học tập số.'],['2023','Mở Jody Music Studio, không gian biểu diễn và thu âm cho học viên.'],['2026','1.200+ học viên, 24 giảng viên và một cộng đồng vẫn đang lớn lên.']]
export default function AboutPage(){
  useSeo({title:'Về Jody Music',description:'Câu chuyện, triết lý giáo dục và đội ngũ của Jody Music.'})
  return <><PageHero eyebrow="Our story" title="Chúng tôi dạy cách lắng nghe." description="Trước khi chơi một nốt nhạc, ta học cách lắng nghe bản thân, người bên cạnh và khoảng lặng giữa những âm thanh." image="https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1400&q=85" /><section className="section-pad bg-white"><div className="container-site grid gap-14 lg:grid-cols-2"><div><p className="eyebrow text-iris">Câu chuyện thương hiệu</p><h2 className="display mt-5 text-6xl text-ink">Bắt đầu từ một căn phòng nhỏ và một câu hỏi lớn.</h2></div><div className="space-y-6 text-base leading-8 text-ink/60"><p>Tại sao việc học nhạc thường bị biến thành áp lực? Jody Music ra đời năm 2017 để tìm một câu trả lời khác: giáo dục có cấu trúc nhưng không cứng nhắc, nghiêm túc nhưng vẫn đầy niềm vui.</p><p>Tên gọi Jody Music đại diện cho một không gian nơi mỗi người được khám phá tiếng nói âm nhạc riêng. Giáo viên biết lùi lại để học viên tự tin thể hiện cá tính, thay vì tạo ra những bản sao.</p></div></div></section><section className="section-pad bg-tangerine"><div className="container-site grid gap-6 md:grid-cols-3"><article className="rounded-[1.5rem] bg-ink p-8 text-white md:col-span-2"><p className="eyebrow text-tangerine">Sứ mệnh</p><h2 className="display mt-8 max-w-3xl text-5xl md:text-7xl">Đưa giáo dục âm nhạc chất lượng đến gần hơn với mọi người.</h2></article><article className="rounded-[1.5rem] bg-paper p-8"><p className="eyebrow text-iris">Triết lý</p><h3 className="mt-8 font-display text-4xl font-semibold text-ink">Cá nhân hóa.<br/>Thực hành thật.<br/>Phản hồi rõ.<br/>Tỏa sáng cùng nhau.</h3></article></div></section><section className="section-pad bg-paper"><div className="container-site"><p className="eyebrow text-iris">Những cột mốc</p><h2 className="display mb-14 mt-5 text-6xl">Một hành trình có nhịp.</h2><div className="border-t border-ink/15">{milestones.map(([year,text])=><div key={year} className="grid gap-5 border-b border-ink/15 py-8 md:grid-cols-[.35fr_1fr]"><span className="font-display text-5xl text-iris">{year}</span><p className="max-w-2xl text-lg leading-8 text-ink/60">{text}</p></div>)}</div></div></section><section className="section-pad bg-white"><div className="container-site"><p className="eyebrow text-iris">Đội ngũ</p><h2 className="display mb-12 mt-5 text-6xl">Những người giữ nhịp.</h2><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{teachers.slice(0,3).map((teacher)=><TeacherCard key={teacher.slug} teacher={teacher}/>)}</div></div></section></>
}
