import { Facebook, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Button } from '../components/common/Button'
import { PageHero } from '../components/common/PageHero'
import { courses } from '../data/courses'
import { useSeo } from '../hooks/useSeo'

export default function ContactPage(){
  const [sent,setSent]=useState(false); useSeo({title:'Liên hệ',description:'Liên hệ DẤU LẶNG Music Academy để được tư vấn khóa học âm nhạc phù hợp.'})
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true)}
  return <><PageHero eyebrow="Come say hello" title="Bắt đầu bằng một cuộc trò chuyện." description="Kể chúng tôi nghe về người học, mục tiêu và bản nhạc yêu thích. Đội ngũ học thuật sẽ giúp bạn tìm bước khởi đầu phù hợp." /><section className="section-pad bg-white"><div className="container-site grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-[2rem] bg-ink p-7 text-white md:p-10"><p className="eyebrow text-tangerine">DẤU LẶNG · Quận 3</p><h2 className="display mt-6 text-5xl">Cánh cửa luôn mở cho những người yêu âm nhạc.</h2><div className="mt-10 space-y-6 text-sm text-white/65">{[[Phone,'(028) 7300 8886','tel:02873008886'],[MessageCircle,'Zalo: 0909 123 456','https://zalo.me'],[Mail,'hello@daulang.edu.vn','mailto:hello@daulang.edu.vn'],[Facebook,'DẤU LẶNG Music Academy','#'],[MapPin,'32A Trần Quốc Thảo, P. Xuân Hòa, TP.HCM','#']].map(([Icon,text,href])=>{const I=Icon as typeof Phone;return <a key={String(text)} href={String(href)} className="focus-ring flex items-start gap-4 hover:text-tangerine"><I size={20} className="shrink-0 text-tangerine"/><span>{String(text)}</span></a>})}</div><div className="mt-12 overflow-hidden rounded-2xl bg-white/10"><div className="staff-lines grid aspect-[4/3] place-items-center text-center"><div><MapPin className="mx-auto text-tangerine"/><p className="mt-3 text-sm font-semibold">Google Map</p><p className="mt-1 text-xs text-white/40">Map embed placeholder</p></div></div></div></div><div className="rounded-[2rem] bg-paper p-7 md:p-10">{sent?<div className="grid h-full min-h-[35rem] place-items-center text-center"><div><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-lime text-3xl">✓</span><h2 className="display mt-7 text-5xl">Tin nhắn đã được gửi.</h2><p className="mt-5 text-ink/55">Chúng tôi sẽ phản hồi bạn trong giờ làm việc gần nhất.</p><Button className="mt-8" onClick={()=>setSent(false)}>Gửi tin nhắn khác</Button></div></div>:<form onSubmit={submit}><p className="eyebrow text-iris">Nhận tư vấn</p><h2 className="display mt-5 text-5xl">Bạn đang tìm khóa học nào?</h2><div className="mt-9 grid gap-5 sm:grid-cols-2"><Field label="Họ và tên" required/><Field label="Số điện thoại" type="tel" required/><Field label="Email" type="email"/><label><span className="mb-2 block text-xs font-semibold text-ink/55">Môn học quan tâm</span><select className="focus-ring h-12 w-full rounded-xl border border-ink/15 bg-white px-4 text-sm"><option>Chọn môn học</option>{courses.map((c)=><option key={c.slug}>{c.name}</option>)}</select></label><Field label="Độ tuổi học viên"/><label className="sm:col-span-2"><span className="mb-2 block text-xs font-semibold text-ink/55">Ghi chú</span><textarea rows={5} className="focus-ring w-full rounded-xl border border-ink/15 bg-white px-4 py-3 text-sm" placeholder="Mục tiêu, khung giờ phù hợp..."/></label></div><Button type="submit" className="mt-7" arrow>Gửi yêu cầu</Button></form>}</div></div></section></>
}
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label><span className="mb-2 block text-xs font-semibold text-ink/55">{label}</span><input {...props} placeholder={label} className="focus-ring h-12 w-full rounded-xl border border-ink/15 bg-white px-4 text-sm"/></label>}
