import { Check, Clock3, GraduationCap, Layers3, Users } from 'lucide-react'
import { Navigate, useParams } from 'react-router-dom'
import { Button } from '../components/common/Button'
import { Breadcrumb } from '../components/common/Breadcrumb'
import { FAQAccordion } from '../components/common/FAQAccordion'
import { SectionHeading } from '../components/common/SectionHeading'
import { TeacherCard } from '../components/cards/TeacherCard'
import { VideoCard } from '../components/cards/VideoCard'
import { courses } from '../data/courses'
import { teachers } from '../data/teachers'
import { performances } from '../data/performances'
import { faqs } from '../data/content'
import { formatCurrency } from '../utils/format'
import { useBooking } from '../context/BookingContext'
import { useSeo } from '../hooks/useSeo'

export default function CourseDetailPage() {
  const { slug } = useParams()
  const course = courses.find((item) => item.slug === slug)
  const { openBooking } = useBooking()
  useSeo({ title: course ? `Khóa học ${course.name}` : 'Không tìm thấy khóa học', description: course?.longDescription ?? 'Khóa học không tồn tại.' })
  if (!course) return <Navigate to="/404" replace />
  const matchedTeachers = teachers.filter((teacher) => teacher.instruments.some((i) => course.category.toLowerCase().includes(i.toLowerCase()) || i.toLowerCase().includes(course.shortName.toLowerCase()))).slice(0,2)
  const selectedTeachers = matchedTeachers.length ? matchedTeachers : teachers.slice(0,2)
  return <><section className="relative overflow-hidden bg-ink pb-16 pt-32 text-white md:pb-24 md:pt-40"><div className="container-site"><Breadcrumb items={[{ label: 'Khóa học', to: '/courses' }, { label: course.name }]} /><div className="mt-12 grid items-end gap-12 lg:grid-cols-[1fr_.9fr]"><div><p className="eyebrow text-tangerine">{course.badge ?? 'Lộ trình cá nhân hóa'}</p><h1 className="display mt-6 text-[clamp(4.5rem,11vw,9.5rem)]">{course.name}</h1><p className="mt-7 max-w-xl text-base leading-8 text-white/60 md:text-lg">{course.longDescription}</p><Button onClick={() => openBooking(course.name)} variant="secondary" className="mt-8" arrow>Học thử {course.name}</Button></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><img src={course.image} alt={`Khóa học ${course.name}`} className="image-cover" fetchPriority="high" /><span className="absolute bottom-5 right-5 rounded-full bg-lime px-4 py-2 text-xs font-bold uppercase tracking-wider text-ink">Từ {formatCurrency(course.priceFrom)}</span></div></div><div className="mt-14 grid grid-cols-2 gap-5 border-t border-white/15 pt-8 md:grid-cols-5">{[[Users,'Độ tuổi',course.age],[Clock3,'Thời lượng',course.duration],[Layers3,'Hình thức',course.format],[GraduationCap,'Trình độ',course.levels.join(' · ')],[Check,'Số buổi',`${course.sessions}+ buổi`]].map(([Icon,label,value]) => { const I = Icon as typeof Users; return <div key={String(label)}><I size={18} className="mb-3 text-tangerine" /><span className="eyebrow text-white/35">{String(label)}</span><p className="mt-2 text-sm leading-6 text-white/75">{String(value)}</p></div>})}</div></div></section>
  <section className="section-pad bg-paper"><div className="container-site grid gap-14 lg:grid-cols-2"><div><p className="eyebrow text-iris">Khóa học dành cho ai</p><h2 className="display mt-5 text-6xl text-ink">Bắt đầu đúng nơi. Tiến bộ đúng nhịp.</h2><p className="mt-6 leading-7 text-ink/60">Dành cho {course.audience.join(', ').toLowerCase()} muốn học {course.name.toLowerCase()} từ nền tảng, chơi những tác phẩm yêu thích hoặc phát triển theo định hướng biểu diễn và chứng chỉ.</p></div><div className="rounded-[2rem] bg-white p-7 md:p-10"><p className="eyebrow text-ink/40">Bạn sẽ học được</p><ul className="mt-7 space-y-5">{course.outcomes.map((outcome) => <li key={outcome} className="flex items-start gap-4 border-b border-ink/10 pb-5 text-lg font-semibold"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-lime"><Check size={15} /></span>{outcome}</li>)}</ul></div></div></section>
  <section className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Lộ trình & giáo trình" title="Từng chặng rõ ràng. Không học trong mơ hồ." /><div className="grid gap-4 md:grid-cols-4">{course.curriculum.map((stage,index) => <article key={stage} className="rounded-2xl border border-ink/12 p-6"><span className="font-display text-5xl text-iris/35">0{index+1}</span><h3 className="mt-12 font-display text-2xl font-semibold text-ink">{stage}</h3><p className="mt-3 text-sm leading-6 text-ink/50">Mục tiêu, bài tập và đánh giá tiến bộ được cá nhân hóa theo từng học viên.</p></article>)}</div></div></section>
  <section className="section-pad bg-paper"><div className="container-site"><SectionHeading eyebrow="Giảng viên đồng hành" title={`Người giúp bạn làm chủ ${course.name}.`} /><div className="grid gap-8 sm:grid-cols-2 lg:max-w-4xl">{selectedTeachers.map((teacher) => <TeacherCard key={teacher.slug} teacher={teacher} />)}</div></div></section>
  <section className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Thành quả học viên" title="Nghe thấy tiến bộ thật." /><div className="grid gap-8 md:grid-cols-2">{performances.slice(0,2).map((item) => <VideoCard key={item.id} item={item} />)}</div></div></section>
  <section className="section-pad bg-paper"><div className="container-site grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-iris">FAQ khóa học</p><h2 className="display mt-5 text-6xl">Trước khi bắt đầu.</h2><div className="mt-8 rounded-2xl bg-ink p-6 text-white"><p className="text-sm text-white/50">Học phí từ</p><p className="mt-2 font-display text-4xl">{formatCurrency(course.priceFrom)}</p><p className="mt-2 text-xs text-white/45">/ gói {course.sessions} buổi · tùy hình thức</p></div></div><FAQAccordion items={faqs.slice(0,6)} /></div></section><div className="sticky bottom-4 z-30 mx-auto mb-4 flex w-[min(calc(100%-2rem),34rem)] items-center justify-between gap-4 rounded-full bg-ink p-2 pl-5 text-white shadow-2xl"><div><p className="text-[.62rem] uppercase tracking-wider text-white/45">Khóa {course.name}</p><p className="text-sm font-semibold">Học thử miễn phí</p></div><Button onClick={() => openBooking(course.name)} variant="secondary">Đăng ký ngay</Button></div></>
}
