import { CalendarDays, MapPin, Play } from 'lucide-react'
import { Navigate, useParams } from 'react-router-dom'
import { Breadcrumb } from '../components/common/Breadcrumb'
import { Button } from '../components/common/Button'
import { events } from '../data/events'
import { useBooking } from '../context/BookingContext'
import { useSeo } from '../hooks/useSeo'

export default function EventDetailPage() {
  const { slug }=useParams(); const event=events.find((item)=>item.slug===slug); const {openBooking}=useBooking()
  useSeo({ title:event?.title??'Không tìm thấy sự kiện', description:event?.description??'Sự kiện không tồn tại.' })
  if(!event) return <Navigate to="/404" replace />
  return <><section className="bg-ink pb-16 pt-32 text-white md:pt-40"><div className="container-site"><Breadcrumb items={[{label:'Sự kiện',to:'/events'},{label:event.title}]} /><div className="mt-12 max-w-5xl"><p className="eyebrow text-tangerine">{event.category}</p><h1 className="display mt-6 text-[clamp(4rem,10vw,9rem)]">{event.title}</h1><div className="mt-8 flex flex-wrap gap-6 text-sm text-white/60"><span className="flex items-center gap-2"><CalendarDays size={18} className="text-tangerine" />{event.date}</span><span className="flex items-center gap-2"><MapPin size={18} className="text-tangerine" />{event.location}</span></div></div></div></section><section className="bg-paper pb-12"><div className="container-site"><div className="relative aspect-[16/8] -translate-y-1 overflow-hidden rounded-[2rem]"><img src={event.image} alt={event.title} className="image-cover" fetchPriority="high" /></div></div></section><section className="section-pad bg-paper"><div className="container-site grid gap-14 lg:grid-cols-[1fr_.55fr]"><article><p className="eyebrow text-iris">Về sự kiện</p><h2 className="display mt-5 text-5xl text-ink">Một ngày để âm nhạc trở thành ký ức.</h2><p className="mt-8 text-lg leading-8 text-ink/60">{event.description} Chương trình được dàn dựng bởi đội ngũ giảng viên và học viên, với hệ thống âm thanh, ánh sáng chuyên nghiệp trong một không gian gần gũi.</p><p className="mt-6 leading-8 text-ink/60">Khán giả sẽ gặp những tiết mục solo, hòa tấu và ban nhạc ở nhiều độ tuổi. Đây không chỉ là một đêm diễn, mà là dịp để gia đình nhìn thấy sự trưởng thành, kiên trì và niềm vui của học viên.</p><button className="focus-ring group relative mt-10 block w-full overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85" alt="Video highlight sự kiện" className="image-cover aspect-video opacity-80" /><span className="absolute inset-0 grid place-items-center"><i className="grid h-16 w-16 place-items-center rounded-full bg-white text-iris"><Play fill="currentColor" /></i></span></button></article><aside className="h-fit rounded-[1.5rem] bg-white p-7 lg:sticky lg:top-28"><p className="eyebrow text-ink/40">Thông tin</p><dl className="mt-6 divide-y divide-ink/10 text-sm"><div className="py-4"><dt className="text-ink/45">Thời gian</dt><dd className="mt-1 font-semibold">19:00 · {event.date}</dd></div><div className="py-4"><dt className="text-ink/45">Địa điểm</dt><dd className="mt-1 font-semibold">{event.location}</dd></div><div className="py-4"><dt className="text-ink/45">Vé tham dự</dt><dd className="mt-1 font-semibold">Miễn phí · Đăng ký trước</dd></div></dl><Button onClick={()=>openBooking()} className="mt-6 w-full">Giữ chỗ</Button></aside></div></section></>
}
