import { Award, GraduationCap, Music2, Quote } from 'lucide-react'
import { Navigate, useParams } from 'react-router-dom'
import { Breadcrumb } from '../components/common/Breadcrumb'
import { Button } from '../components/common/Button'
import { CourseCard } from '../components/cards/CourseCard'
import { courses } from '../data/courses'
import { teachers } from '../data/teachers'
import { useBooking } from '../context/BookingContext'
import { useSeo } from '../hooks/useSeo'

export default function TeacherDetailPage() {
  const { slug } = useParams(); const teacher = teachers.find((item) => item.slug === slug); const { openBooking } = useBooking()
  useSeo({ title: teacher?.name ?? 'Không tìm thấy giáo viên', description: teacher ? `${teacher.role} — ${teacher.experience} tại DẤU LẶNG Music Academy.` : 'Giáo viên không tồn tại.' })
  if (!teacher) return <Navigate to="/404" replace />
  const teachingCourses = courses.filter((course) => teacher.instruments.some((i) => course.category.includes(i) || course.name.includes(i))).slice(0,3)
  return <><section className="bg-paper pb-20 pt-32 md:pt-40"><div className="container-site"><Breadcrumb items={[{ label: 'Giáo viên', to: '/teachers' }, { label: teacher.name }]} /><div className="mt-12 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><img src={teacher.image} alt={teacher.name} className="image-cover" fetchPriority="high" /><span className="absolute bottom-5 left-5 rounded-full bg-lime px-4 py-2 text-xs font-bold uppercase">{teacher.instruments.join(' · ')}</span></div><div className="flex flex-col justify-end"><p className="eyebrow text-iris">{teacher.role}</p><h1 className="display mt-6 text-[clamp(4rem,9vw,8rem)] text-ink">{teacher.name}</h1><div className="mt-9 grid gap-4 sm:grid-cols-3">{[[Award,teacher.experience],[GraduationCap,teacher.education],[Music2,teacher.certificate]].map(([Icon,text]) => { const I=Icon as typeof Award; return <div key={String(text)} className="rounded-2xl bg-white p-5"><I size={20} className="text-iris" /><p className="mt-5 text-sm font-semibold leading-6">{String(text)}</p></div> })}</div><blockquote className="mt-9 flex gap-4 border-l-2 border-tangerine pl-6 font-display text-3xl leading-snug text-ink/75"><Quote className="shrink-0 text-tangerine" />“{teacher.quote}”</blockquote><Button onClick={() => openBooking(teacher.instruments[0])} className="mt-9 self-start" arrow>Học thử cùng giảng viên</Button></div></div></div></section><section className="section-pad bg-ink text-white"><div className="container-site grid gap-14 lg:grid-cols-2"><div><p className="eyebrow text-tangerine">Phương pháp giảng dạy</p><h2 className="display mt-6 text-6xl">Kỷ luật trong kỹ thuật. Tự do trong biểu đạt.</h2></div><div className="space-y-7 text-base leading-8 text-white/60"><p>{teacher.name} xây dựng buổi học từ mục tiêu thật của học viên, kết hợp nền tảng học thuật với repertoire gần gũi để mỗi kỹ thuật mới đều có ngữ cảnh âm nhạc rõ ràng.</p><p>Học viên được phản hồi cụ thể sau từng buổi, theo dõi bằng video và báo cáo tiến bộ. Không so sánh với người khác — chỉ so với chính phiên bản của mình tuần trước.</p></div></div></section><section className="section-pad bg-white"><div className="container-site"><p className="eyebrow text-iris">Khóa học đang dạy</p><h2 className="display mb-12 mt-5 text-6xl text-ink">Cùng bắt đầu.</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{(teachingCourses.length ? teachingCourses : courses.slice(0,3)).map((course,index) => <CourseCard key={course.slug} course={course} index={index} />)}</div></div></section></>
}
